### ISSUE TITLE
awz3格式问题

### ISSUE THREAD

**Issue by Biercenter** [qq573011406/ebookdownloader#3]
你好，我用 .\ebookdownloader.exe --bookid=74_74821 --awz3 命令生成的文件是在tmp目录，没有生成outputs目录，加上 --txt的话可以生成outputs目录，里边有.txt和.awz3文件。但是.awz3文件拖到calibre没用，需要修改后缀为.azw3。 
还有一个行首缩进问题，我在easypub上用同样的css生成后没问题。百度了下说需要把空格半角改成全角。
谢谢！

**Comment by sndnvaps** [comment]
文件后序问题，我现在处理一下。。 
无法生成 outputs目录问题，你截最后的屏幕显示我看看，是什么问题。
@Biercenter 多谢反馈

**Comment by sndnvaps** [comment]
:bug: 已经被修改 
修改提交https://github.com/qq573011406/ebookdownloader/commit/0193721f787c73c4a8d3fceefa88e01898176f8f

已经已经被解决了。
